runtime: go
api_version: go1

handlers:
- url: /public
  static_dir: public
- url: /.*
  script: _go_app
  secure: always

skip_files:
- .git
- .DS_Store
- .env
- .envrc
- app.prod.yaml
- check
- tests-integration

env_variables: